### ISSUE TITLE
classFontTitle

### ISSUE THREAD

**Issue by tsulim** [XinYang-YXY/denoshop#7]
Where's that class located at?

**Comment by xy-241** [comment]
May I have a more detailed description of it?
Do you mean the class used in the CSS? What did the inspect returns?

**Comment by tsulim** [comment]
yeah the class named "classFontTitle"
`<legend class="border-bottom mb-4 shopFontTitle">Checkout</legend>`

**Comment by tsulim** [comment]
oh shyt nvm, it's called shopFontTitle, no wonder couldn't find, im sorry to bother u omo
